name: Build Windows Tray — v17 (shim only)

on:
  workflow_dispatch:

jobs:
  make-ffmpeg-shim:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create check-ffmpeg.ts safely (PowerShell here-string)
        run: |
          $ffmpegPath = "apps/whispering/src/routes/(config)/+layout/check-ffmpeg.ts"
          $dir = Split-Path $ffmpegPath
          if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Force -Path $dir | Out-Null
          }

          $content = @'
          export type FfmpegCheck = { available: boolean; version?: string; error?: string };
          export async function checkFfmpeg(): Promise<FfmpegCheck> {
            return { available: true, version: "CI" };
          }
          export function hasNavigatorLocalTranscriptionIssue(): boolean {
            return false;
          }
          export default checkFfmpeg;
          '@

          Set-Content -Path $ffmpegPath -Value $content -Encoding UTF8
          Write-Host "✅ Wrote $ffmpegPath"

      - name: Show file back (for sanity)
        run: |
          Get-Content "apps/whispering/src/routes/(config)/+layout/check-ffmpeg.ts"
