name: Build Windows Tray v16d (winget Vulkan, safe shim)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Tauri CLI (global)
        run: |
          bun add -g @tauri-apps/cli
          tauri -V

      - name: Install Vulkan SDK (LunarG) via winget
        run: |
          winget source update
          winget install --id LunarG.VulkanSDK --accept-package-agreements --accept-source-agreements --silent
          $root = "C:\VulkanSDK"
          if (!(Test-Path $root)) { throw "VulkanSDK root non trovato in $root" }
          $dirs = Get-ChildItem $root -Directory | Sort-Object Name -Descending
          if ($dirs.Count -eq 0) { throw "Nessuna versione VulkanSDK trovata in $root" }
          $sdk = $dirs[0].FullName
          "VULKAN_SDK=$sdk"   | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          "VK_SDK_PATH=$sdk"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          "PATH=$($sdk)\Bin;$Env:PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "✅ Vulkan SDK in $sdk"

      - name: Add FFmpeg check shim (line-by-line, no YAML tricks)
        run: |
          $ffmpegPath = "apps/whispering/src/routes/(config)/+layout/check-ffmpeg.ts"
          $ffmpegDir  = Split-Path $ffmpegPath
          if (-not (Test-Path $ffmpegDir)) { New-Item -ItemType Directory -Force -Path $ffmpegDir | Out-Null }
          Set-Content -Path $ffmpegPath -Value 'export type FfmpegCheck = { available: boolean; version?: string; error?: string };' -Encoding UTF8
          Add-Content -Path $ffmpegPath -Value ''
          Add-Content -Path $ffmpegPath -Value 'export async function checkFfmpeg(): Promise<FfmpegCheck> {'
          Add-Content -Path $ffmpegPath -Value '  return { available: true, version: "CI" };'
          Add-Content -Path $ffmpegPath -Value '}'
          Add-Content -Path $ffmpegPath -Value 'export function hasNavigatorLocalTranscriptionIssue(): boolean {'
          Add-Content -Path $ffmpegPath -Value '  return false;'
          Add-Content -Path $ffmpegPath -Value '}'
          Add-Content -Path $ffmpegPath -Value 'export default checkFfmpeg;'
          Write-Host "✅ Shim scritto in $ffmpegPath"

      - name: Install JS deps (root)
        run: |
          bun install --frozen-lockfile
          Write-Host "✅ Root deps installed"

      - name: Build Whispering (SSR only)
        working-directory: apps/whispering
        run: |
          bun run build
          Write-Host "✅ Whispering SSR built"

      - name: Build Tauri (Windows)
        working-directory: apps/whispering
        env:
          VULKAN_SDK: ${{ env.VULKAN_SDK }}
          VK_SDK_PATH: ${{ env.VK_SDK_PATH }}
          NODE_ENV: production
        run: |
          tauri build
          Write-Host "✅ Tauri build done"

      - name: Upload artifact (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: whispering-windows-with-tray
          path: apps/whispering/src-tauri/target/release/*.exe
