name: Build Whispering (Windows) — CPU-only Tray
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-whispering-windows-tray:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install WiX (for MSI)
        run: |
          choco install wixtoolset --yes --no-progress
          if (-not (Test-Path "C:\Program Files (x86)\WiX Toolset v3.14\bin")) { throw "WiX non trovato" }

      # ---- Patch: forza CPU-only (nessun Vulkan) in Cargo.toml ----
      - name: Force CPU-only (no Vulkan) in Cargo.toml
        working-directory: apps/whispering/src-tauri
        run: |
          $f="Cargo.toml"
          if (-not (Test-Path $f)) { throw "Cargo.toml non trovato in src-tauri" }
          $t = Get-Content $f -Raw
          $t = $t -replace 'features\s*=\s*\[\s*"vulkan"\s*\]', 'default-features = false'
          $t = $t -replace '(^\s*whisper-rs\s*=\s*"\d+[^"]*"\s*$)', 'whisper-rs = { version = "0.11", default-features = false }'
          $t = $t -replace '(^\s*whisper-rs-sys\s*=\s*"\d+[^"]*"\s*$)', 'whisper-rs-sys = { version = "0.11.1", default-features = false }'
          $t = $t -replace 'whisper-rs\s*=\s*\{\s*version\s*=\s*"([^"]+)"\s*(,\s*features\s*=\s*\[[^\]]*\])?\s*\}', 'whisper-rs = { version = "$1", default-features = false }'
          $t = $t -replace 'whisper-rs-sys\s*=\s*\{\s*version\s*=\s*"([^"]+)"\s*(,\s*features\s*=\s*\[[^\]]*\])?\s*\}', 'whisper-rs-sys = { version = "$1", default-features = false }'
          Set-Content $f $t -Encoding UTF8
          Write-Host "✅ Cargo.toml forzato CPU-only"

      # ---- Shim ffmpeg: scritto come array di righe per evitare problemi YAML ----
      - name: Add tiny ffmpeg shim (only if missing)
        working-directory: apps/whispering
        run: |
          $dir = "src/routes/(config)/+layout"
          New-Item -ItemType Directory -Force -Path $dir | Out-Null
          $ff  = Join-Path $dir "check-ffmpeg.ts"
          if (-not (Test-Path $ff)) {
            $lines = @(
              'export async function hasNavigatorLocalTranscriptionIssue() {'
              '  // Shim per CI: nessun problema di ffmpeg su Windows runner'
              '  return false;'
              '}'
            )
            Set-Content -Path $ff -Value $lines -Encoding UTF8
            Write-Host "Created shim check-ffmpeg.ts"
          } else {
            Write-Host "Shim già presente."
          }

      - name: Bun install (workspace)
        run: bun install --frozen-lockfile || bun install

      - name: Bun install (whispering app)
        working-directory: apps/whispering
        run: bun install --frozen-lockfile || bun install

      - name: Build Whispering UI (SSR)
        working-directory: apps/whispering
        env:
          NODE_ENV: production
        run: bun run build

      - name: Build Tauri bundle (CPU-only)
        working-directory: apps/whispering
        env:
          RUSTFLAGS: "-C target-cpu=native"
        run: |
          bunx --bun @tauri-apps/cli@latest tauri build
          Write-Host "Done Tauri build"

      - name: Upload installer artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: whispering-windows-tray
          path: |
            apps/whispering/src-tauri/target/release/bundle/**/*.exe
            apps/whispering/src-tauri/target/release/bundle/**/*.msi
            apps/whispering/src-tauri/target/release/bundle/**/*.zip
          if-no-files-found: warn
