name: Build Whispering (Windows) with Tray (no-merge, no-conflicts) — v2

on:
  workflow_dispatch:

jobs:
  build-tray-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash   # forza bash per tutti gli step "run"

    steps:
      - name: Checkout (placeholder)
        uses: actions/checkout@v4

      - name: Clone upstream epicenter (latest main)
        run: |
          git clone https://github.com/epicenter-md/epicenter.git epicenter-up
          cd epicenter-up
          git fetch --all --prune
          git checkout origin/main -B tray-build

      - name: Add tray feature remote & fetch
        run: |
          cd epicenter-up
          git remote add tray https://github.com/vishesh-sachan/epicenter.git
          git fetch tray feature/minimize-to-tray

      - name: Merge tray feature preferring tray on conflicts
        run: |
          cd epicenter-up
          # Configura identità per eventuale commit di merge
          git config user.name "tray-bot"
          git config user.email "tray-bot@users.noreply.github.com"
          # Unione automatica: in caso di conflitti preferisci le modifiche della tray
          git merge --no-edit -X theirs tray/feature/minimize-to-tray || true
          # Se ci sono file non indicizzati o merge sospeso, forza l’add + commit
          git add -A || true
          git commit -m "Temp merge: upstream main + tray feature for build" || true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('epicenter-up/**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Install deps (monorepo)
        working-directory: epicenter-up
        run: bun install

      # usa sempre la CLI tauri via bunx per evitare "tauri: command not found"
      - name: Build Whispering (Windows + Tray)
        working-directory: epicenter-up/apps/whispering
        run: bunx --bun @tauri-apps/cli@latest tauri build

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: whispering-windows-with-tray
          path: |
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.msi
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.exe
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.zip
