name: Build Whispering (Windows) with Tray (no-merge, no-conflicts)

on:
  workflow_dispatch:
  # se vuoi compilarlo automaticamente ad ogni push nel tuo fork, lascia anche:
  # push:
  #   branches: [ main ]

jobs:
  build-tray-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout (placeholder)
        uses: actions/checkout@v4

      - name: Clone upstream epicenter (latest main)
        run: |
          git clone https://github.com/epicenter-md/epicenter.git epicenter-up
          cd epicenter-up
          git fetch --all
          git checkout origin/main -B tray-build

      - name: Add tray feature remote & fetch
        run: |
          cd epicenter-up
          git remote add tray https://github.com/vishesh-sachan/epicenter.git
          git fetch tray feature/minimize-to-tray

      - name: Merge tray feature preferring tray on conflicts
        shell: bash
        run: |
          cd epicenter-up
          # Unione "automatica" che in caso di conflitti sceglie i cambi della tray
          git merge --no-edit -X theirs tray/feature/minimize-to-tray || true
          # forza il completamento in caso restino file non indicizzati
          git add -A || true
          git commit -m "Temp merge: upstream main + tray feature for build" || true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust (Tauri)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('epicenter-up/**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Install deps (monorepo)
        working-directory: epicenter-up
        run: bun install

      - name: Build Whispering (Windows + Tray)
        working-directory: epicenter-up/apps/whispering
        run: bun tauri build

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: whispering-windows-with-tray
          path: |
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.msi
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.exe
            epicenter-up/apps/whispering/src-tauri/target/release/bundle/**/*.zip
